Repository edvinnn/Green-Power, pull requests merged in 2019-12, with the labels that each got.

#41 Integrate with AWS
  .github/workflows/deploy.yml
  Dockerfile
  README.md
  package.json
  simulator/simulator.js
Labels: crucial, deployment

#46 Update README.md
  README.md
Labels: documentation

#49 Update deploy.yml
  .github/workflows/deploy.yml
Labels: backend, bug, crucial, deployment

#48 Prosumer simulator
  server/api/routes.js
  server/model.js
  server/server_db_utils.js
  server/sim_db_utils.js
  simulator/api/routes.js
  simulator/server_db_utils.js
  simulator/simulator.js
Labels: backend, enhancement, simulator

#53 HTML templating
  server/website/routes.js
  views/dash.ejs
  views/dashboard.ejs
  views/index.ejs
  views/login.ejs
  views/modules/dashboard_main.ejs
  views/modules/head.ejs
  views/modules/logout_prompt.ejs
  views/modules/sidebar.ejs
  views/modules/topbar.ejs
  views/register.ejs
Labels: enhancement, frontend

#52 Websockets implementation
  package.json
  server/api/routes.js
  server/server.js
  server/server_db_utils.js
  server/website/routes.js
  views/modules/dashboard_main.ejs
  views/modules/dashboard_scripts.ejs
  yarn.lock
Labels: backend, enhancement, frontend

#56 Dashboard updates with real time values from web socket
  server/api/routes.js
  views/modules/dashboard_main.ejs
  views/modules/dashboard_scripts.ejs
Labels: backend, frontend

#37 Time Report Hampus
  time_reports/time_report_hampus.md
Labels: documentation

#58 Attempt to fix promiseRejectionWarning
  server/api/routes.js
  server/server.js
  simulator/sim_db_utils.js
Labels: backend, bug, crucial, deployment

#60 Added chart functionality for latest winds
  server/api/routes.js
  views/modules/dashboard_scripts.ejs
  views/modules/winds_chart_script.ejs
Labels: enhancement, frontend

#61 Api routes for ratio
  server/api/routes.js
Labels: backend

#63 Slider for ratios
  server/api/routes.js
  server/website/routes.js
  views/modules/dashboard_main.ejs
  views/modules/dashboard_scripts.ejs
Labels: backend, frontend

#69 Redirect authenticated users from index to dashboard
  server/website/routes.js
Labels: enhancement

#72 Winds chart wrong order bugfix
  views/modules/dashboard_scripts.ejs
Labels: bug

#71 Simulator improvements
  simulator/simulator.js
Labels: simulator

#70 Mobile view topbar bug-fix
  views/modules/topbar.ejs
Labels: frontend

#62 Update README.md
  README.md
Labels: documentation

#73 Release patch 1
  README.md
  simulator/simulator.js
  views/modules/dashboard_scripts.ejs
  views/modules/topbar.ejs
Labels: deployment

#75 Simulator buffer
  simulator/simulator.js
Labels: bug, simulator

#79 Introduced manager
  server/api/routes.js
  server/model.js
  server/server_db_utils.js
  server/website/routes.js
  simulator/simulator.js
  views/manager-dashboard.ejs
Labels: backend, crucial, enhancement

#84 Iterates trough users with same email
  server/passport-config.js
Labels: PANIC!!!, Priority high, backend, bug, crucial, enhancement

#90 Web-socket automatically updates prosumer dashboards
  package.json
  server/api/routes.js
  server/server.js
  server/server_db_utils.js
  simulator/simulator.js
  views/modules/dashboard_scripts.ejs
  yarn.lock
Labels: backend, crucial, enhancement, simulator

#94 Email converted to lowercase
  server/passport-config.js
  server/website/routes.js
Labels: backend, bug

#99 Production panel of manager dashboard
  server/api/routes.js
  views/modules/manager/dashboard.ejs
  views/modules/manager/dashboard_scripts.ejs
Labels: backend, crucial, enhancement

#92 Buffer bug
  simulator/simulator.js
Labels: Priority high, bug, simulator
