Repository edvinnn/Green-Power, pull requests merged in 2019-11, with the labels that each got.

#6 Setup MongoDB and REST boilerplate
  package.json
  simulator/api/controllers/simulatorController.js
  simulator/api/models/simulatorModel.js
  simulator/api/routes/simulatorRoutes.js
  simulator/server.js
  simulator/simulator.js
  yarn.lock
Labels: mongodb, nodejs

#8 Updated time reports
  TIMEREPORT.md
  time_reports/time_report_edvin.md
  time_reports/time_report_hampus.md
Labels: documentation

#13 Consumer model and prosumer consumption put
  server/api/routes.js
  server/model.js
  server/simulator.js
Labels: mongodb, nodejs, simulator

#12 Update time_report_hampus.md
  time_reports/time_report_hampus.md
Labels: documentation

#23 Added functionality to sign in and sign out prosumer
  package.json
  server/passport-config.js
  server/server.js
  server/website/routes.js
  views/index.ejs
  views/login.ejs
  yarn.lock
Labels: enhancement, mongodb, nodejs

#24 Bugfixes and improvements simulator
  package.json
  simulator/server.js
  simulator/simulator.js
Labels: bug, enhancement, mongodb, nodejs

#25 Added current price
  simulator/simulator.js
Labels: simulator

#32 Updated models for prosumer and simulator
  server/api/routes.js
  server/model.js
  simulator/api/routes.js
  simulator/model.js
  simulator/simulator.js
Labels: backend, enhancement, mongodb

#35 Divided connections from server into two different files to handle different connections
  server/api/routes.js
  server/server.js
  server/server_db_utils.js
  server/sim_db_utils.js
  server/website/routes.js
Labels: backend, mongodb, nodejs

#26 Time Report Hampus
  time_reports/time_report_hampus.md
Labels: documentation

#39 Production simulator
  server/model.js
  simulator/model.js
  simulator/server_db_utils
  simulator/server_db_utils.js
  simulator/sim_db_utils.js
  simulator/simulator.js
Labels: mongodb, simulator

#44 logs connection to database
  server/model.js
  server/server_db_utils.js
  server/sim_db_utils.js
  simulator/model.js
Labels: mongodb
