Repository edvinnn/Green-Power, pull requests merged in 2020-01, with the labels that each got.

#102 Price panel of manager dashboard
  server/api/routes.js
  simulator/model.js
  simulator/sim_db_utils.js
  simulator/simulator.js
  views/modules/manager/dashboard.ejs
  views/modules/manager/dashboard_scripts.ejs
Labels: Priority medium, backend, crucial, enhancement

#103 Manager Dashboard: Production Panel
  server/api/routes.js
  server/model.js
  server/server_db_utils.js
  server/website/routes.js
  simulator/simulator.js
  views/modules/manager/dashboard.ejs
  views/modules/manager/dashboard_scripts.ejs
Labels: Priority high, backend, crucial, enhancement

#111 Profile picture
  .gitignore
  package.json
  server/api/routes.js
  server/model.js
  server/server.js
  server/server_db_utils.js
  server/website/routes.js
  views/modules/profile_main.ejs
  views/modules/topbar.ejs
  yarn.lock
Labels: Mandatory

#112 Change password
  server/api/routes.js
  server/server_db_utils.js
  views/modules/form_checking_scripts.ejs
  views/modules/profile_main.ejs
  views/profile.ejs
  views/register.ejs
Labels: Mandatory

#114 Blackout mastodont fix
  server/model.js
  server/server_db_utils.js
  server/website/routes.js
  simulator/simulator.js
Labels: Mandatory

#115 Initial Prosumer List
  server/api/routes.js
  server/model.js
  server/server_db_utils.js
  server/website/routes.js
  views/modules/manager/dashboard.ejs
  views/modules/manager/list.ejs
  views/modules/manager/prosumer_list_scripts.ejs
Labels: Mandatory

#116 Finalized prosumer list and minor bug fixes
  server/api/routes.js
  server/model.js
  server/server_db_utils.js
  simulator/simulator.js
  views/index.ejs
  views/login.ejs
  views/modules/dashboard_main.ejs
  views/modules/dashboard_scripts.ejs
  views/modules/manager/dashboard.ejs
  views/modules/manager/dashboard_scripts.ejs
  views/modules/manager/prosumer_list_scripts.ejs
  views/modules/profile_main.ejs
  views/modules/topbar.ejs
  views/register.ejs
Labels: Mandatory

#119 Update README.md
  README.md
Labels: documentation

#120 removed old password input
  views/modules/profile_main.ejs
Labels: frontend

#117 added env file for default localhost
  .env
  .gitignore
Labels: documentation, enhancement

#66 Update time_report_hampus.md
  time_reports/time_report_hampus.md
Labels: documentation

#64 Update time_report_edvin.md
  time_reports/time_report_edvin.md
Labels: documentation

#121 Report added to repo
  Report.pdf
Labels: documentation

#122 Updated report
  Report.pdf
Labels: documentation
